require: rubocop-rails

AllCops:
  Exclude:
    - bin/*
    - config/initializers/*
    - db/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - spec/swagger_helper.rb
    - Gemfile

Metrics/BlockLength:
  Exclude:
    - 'spec/requests/**/*.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false 
