require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/*
    - config/initializers/*
    - db/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - spec/swagger_helper.rb
    - Gemfile
    - vendor/bundle/**/*

Metrics/BlockLength:
  Exclude:
    - 'spec/requests/**/*.rb'
    - config/environments/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false 
